### ISSUE TITLE
Remarks section not colourised

### ISSUE THREAD

**Issue by spgennard** [RechInformatica/rech-editor-cobol#3]
It looks like:

![image](https://user-images.githubusercontent.com/5991192/51144207-525c3f80-1848-11e9-9a33-d923e983d869.png)

Using
 ```cobol
       Identification Division.
       Program-ID.  IndexedData.
       Remarks.

           This program creates an indexed file with keys from 0001 to
           1000.

           The keys are created in random order, and captured in that
           random order to a text file called RandomKeys.txt.

           The RandomKeys.txt file will feed a later process that needs
           to read the records in random order for comparison to reading
           the same information in random order after it's been loaded
           into a table.

       Environment Division.
       Configuration Section.
       Input-Output Section.
```

**Comment by GustavoASC** [comment]
@spgennard
I believe modifying **.\syntaxes\COBOL.tmLanguage.json** will solve this issue because we write on this file regular expressions to colorize and identify COBOL keywords.

Since we've got a _big backlog_, could I ask you to modify this file and make a pull request, please?

It would help us and we would appreciate it! :)

**Comment by spgennard** [comment]
Closing, no action required
